name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # context: ./jenkins-master-slave/externals/
          file: ./jenkins-master-slave/externals/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jenkins-sidecar-config:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/jenkins-sidecar-config:0.0.1